export default {
  normal: "#A0A978",
  fire: "#DB8E1D",
  water: "royalblue",
  grass: "#77C857",
  flying: "#A592D3",
  fighting: "firebrick",
  poison: "purple",
  electric: "yellow",
  ground: "burlywood",
  rock: "#B6A123",
  psychic: "#F05881",
  ice: "#92D6DA",
  bug: "yellowgreen",
  ghost: "#69598E",
  steel: "#AFB3CF",
  dragon: "mediumslateBlue",
  dark: "slategrey",
  fairy: "#FF88EE",
  bird: "#A592D3"
};
